DATA_DISTRIBUTION_FIX = "fix"

DATA_DISTRIBUTION_IID = "iid"
DATA_DISTRIBUTION_IID_DIFF_QUANTITY = "iid-diff-quantity"

DATA_DISTRIBUTION_N_10 = "10"
DATA_DISTRIBUTION_N_20 = "20"
DATA_DISTRIBUTION_N_30 = "30"
DATA_DISTRIBUTION_N_40 = "40"
DATA_DISTRIBUTION_N_50 = "50"
DATA_DISTRIBUTION_N_60 = "60"
DATA_DISTRIBUTION_N_70 = "70"
DATA_DISTRIBUTION_N_80 = "80"
DATA_DISTRIBUTION_N_90 = "90"
DATA_DISTRIBUTION_DIR = "dir"

DATA_DISTRIBUTION_REAL_FEMNIST = "real"

DATA_DISTRIBUTION_STANDARD_IID_HOMO = "homo"
DATA_DISTRIBUTION_STANDARD_IID_DIFF = "iid-diff-quantity"
DATA_DISTRIBUTION_STANDARD_NON_IID_DIR = "noniid-labeldir"