title: Red Federated Learning Framework
description: A Production-Grade Federated Learning Framework with Ray
author: 
  name: Red Project Team
  email: mohammadmojtabaroshani@outlook.com
url: "https://mmroshani.ir"
baseurl: "/red"

# Build settings
markdown: kramdown
highlighter: rouge
theme: just-the-docs

# Kramdown configuration
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge

# Theme settings
just_the_docs:
  # Color scheme supports "light" (default) and "dark"
  color_scheme: light
  
  # Enable or disable the search
  search_enabled: true
  
  # Heading anchor links appear on hover over h1-h6 tags
  heading_anchors: true
  
  # Enable or disable the back-to-top button
  back_to_top: true
  
  # Enable or disable the back-to-top button text
  back_to_top_text: "Back to top"
  
  # Footer content
  footer_content: "Copyright &copy; 2024 Red Project Team. Distributed by <a href=\"https://github.com/mmroshani/red\">GitHub</a>"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-avatar
  - jemoji
  - jekyll-paginate
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/mmroshani/red
    hide_icon: false

# SEO settings
twitter:
  username: 
facebook:
  username: 

# GitHub settings
github_username: mmroshani
repository: mmroshani/red

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CNAME

# Mermaid configuration
mermaid:
  # Version of mermaid library to use
  version: "10.6.1"
  # Theme can be default, neutral, dark, forest, etc.
  theme: default 